# Generated by Django 3.2.9 on 2022-08-22 11:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sliced', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='sub_services',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='bookingdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 16, 32, 4, 240659)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='subservice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subId', to='sliced.sub_services'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_services',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_id', to='sliced.services'),
        ),
        migrations.AlterUniqueTogether(
            name='sub_services',
            unique_together={('service_id', 'name')},
        ),
    ]
